Repository ZahraArshia/book-flight-frontend, pull requests merged in 2022-07, with the labels that each got.

#11 Main page
  package-lock.json
  package.json
  src/App.js
  src/components/Homepage.js
  src/redux/configureStore.js
  src/redux/flights/flights.js
  src/redux/users/users.js
Labels: enhancement

#18 Main page slider
  package-lock.json
  package.json
  src/components/CustomArrows.js
  src/components/Homepage.js
Labels: enhancement

#22 Delete item
  src/App.js
  src/components/AddItem.js
  src/components/DeleteItem.js
  src/components/Homepage.js
  src/redux/flights/flights.js
Labels: enhancement

#24 add details page styles and back button
  src/App.css
  src/components/ItemDetails.js
Labels: Styling

#25 Items styles
  src/App.css
  src/components/AddItem.js
  src/components/DeleteItem.js
Labels: Styling

#28 update readme
  README.md
Labels: documentation
